#ifndef SERVICEINFO_H
#define SERVICEINFO_H

#define HOST_RESOLVE_FAIL 1
#define OPEN_TCPSOCKET_FAIL 2
#define SERVER_HAS_BEEN_OPEN -1
#define PROTOCOL_VERSION 1
#define OK 0

#define MAX_USER_IN_ONCE 64
#define SERVER_BUFF_SIZE 512
#define MAX_MESSAGE_LEN 2048

#endif